#̷\  ===================================================================
#̷\  PowerShell Module -- PowerShell.Module.FontsManager
#̷\  
#̷\  Manifest File Generated on Sat, 27 Sep 2025 03:39:57 GMT
#̷\  Current Git Revision HEAD
#̷\  ===================================================================


@{


    RootModule        =  'PowerShell.Module.FontsManager.psm1'

    ModuleVersion     = '1.7.164'

    GUID              = 'd1d89cdc-2c03-48f9-9478-9a07a9e75578'

    CompanyName       = 'Unknown'

    Author            = 'Guillaume Plante'

    Copyright         = '(c) 2020 Guillaume Plante. All rights reserved.'

    Description       = 'MODULE PowerShell.Module.FontsManager on 7:43 PM'

    PowerShellVersion = '5.0'

    RequiredAssemblies = @()

    # Private data to pass to the module specified in RootModule. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('PowerShell.Module.FontsManager')
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/arsscriptum/PowerShell.Module.FontsManager/blob/main/COPYING'
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/arsscriptum/PowerShell.Module.FontsManager'
        } # End of PSData hashtable
    } # End of PrivateData hashtable


    #̷\  ===================================================
    #̷\     ＭＯＤＵＬＥ ＥＸＰＯＲＴＥＤ ＦＵＮＣＴＩＯＮＳ
    #̷\  ===================================================

	# !NOTE! --- The following functions declaration was automatically generated by the build script. ---
	FunctionsToExport = @(

		# --- Exported Functions from DaFontsSearch.ps1 ---
		"Register-HtmlAgilityPack3b",
		"Remove-NonAlphanumericAndAccents",
		"Invoke-DaFontsSearch",

		# --- Exported Functions from FontCategory.ps1 ---
		"Get-FontSubCategoryIdFromString",
		"Get-FontCategoryStringFromId",
		"Get-FontMainCategoryFromId",
		"Get-FontMainAndSubCategoryFromId",

		# --- Exported Functions from InstallFonts.ps1 ---
		"Install-FontsFromZips",
		"Get-RealFontNameFromFile",
		"Publish-NewFontNotification",
		"Register-NewFonts",
		"Test-IsAdmin",
		"Register-FontInstallerType",

		# --- Exported Functions from ListFonts.ps1 ---
		"Get-FontPreviewPicturePath",
		"Get-FontCategories",
		"Invoke-BatchDownloadFontsPreview",
		"Invoke-DownloadFontsPreviews",
		"Show-Title",
		"Show-ImagePreviewDialog",
		"Open-PreviewLocalPicture",
		"Get-FontsModuleTmpScriptsDirectory",
		"Save-FontPreviewToLocalDisk",
		"Show-ImagesPreviewDialog",
		"Get-daFontsPreviewUrls",
		"Invoke-ListDafontFonts",
		"Open-PreviewLocalPicture",
		"Get-IrfaViewPath",
		"Register-HtmlAgilityPack2a",
		"Get-ExternalsLibraryPath",
		"Get-FontsModuleTemporaryDirectory",

		# --- Exported Functions from SearchFonts.ps1 ---
		"Show-FontPreview",
		"Test-RenderedFonts",
		"Export-FontPreviewHtml",
		"Save-ExportedFontZipMapToJson",
		"Get-InstalledFontsListFromRegistry",
		"Search-FontByName",
		"Get-CustomfontsRealNamesList",
		"Get-FontFamilyFromZip",
		"Export-FontZipMapToJson",
		"Update-FontsRealNamesRegistry")
	

    #̷\  ===================================================
    #̷\     ＴＨＥ ＬＩＳＴ ＯＦ ＥＸＰＯＲＴＥＤ ＡＬＩＡＳＥＳ
    #̷\  ===================================================

	# !NOTE! --- The following alias declaration was automatically generated by the build script. ---
	# List of all aliases packaged with this module

	AliasesToExport = @()

    #̷\  ===================================================
    #̷\     ＴＨＥ ＬＩＳＴ ＯＦ ＦＩＬＥＳ 
    #̷\ （ＩＦ ＣＯＭＰＲＥＳＳＥＤ， ＷＩＬＬ ＢＥ ＥＭＰＴＹ）
    #̷\  ===================================================

	FileList = @()

}




